name: my-survey-app

services:
  react-app:
    build: 
      context: ./my-survey-app
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "5173:5173" # For development
    environment:
      - MONGODB_URL=mongodb://root:example@mongodb:27017/surveyDB
    depends_on:
      - backend
      - mongodb

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000" # Adjust this to match your backend server's port
    environment:
      - MONGODB_URL=mongodb://root:example@mongodb:27017/surveyDB
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB port
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example